### ISSUE TITLE
Allow ordering of source/measure results list

### ISSUE THREAD

**Issue by technivore** [nuitrcs/changing-tides#7]
On the source list/search page and measure list/search page there is currently no way to order the results. Allow users to order by the appropriate fields (date created, date last edited, source publication date, state, etc.)

This should be accomplished by clicking on a column header in the table, and the results should be carried through to subsequent pages if the result set is paginated.

**Comment by technivore** [comment]
Make sure this works for all top-level entities: sources, measures, events, and actors.

**Comment by nambug** [comment]
Finished!
