### ISSUE TITLE
Add Event Search to Measures Event tab

### ISSUE THREAD

**Issue by cmaimone** [nuitrcs/changing-tides#92]
Measures could need to be linked to an existing event.  Currently, the Measures > Event tab only has an option to add an event.  Add ability to search for an event as is being done for Sources > Events.  This could be in addition to the fields to create a new event, or possibly to replace it (so that you add events first from an event tab if you want to add one).

**Comment by technivore** [comment]
Closed in 0092143

**Comment by technivore** [comment]
Remove event form -- make it work like Source, with + link to add new Event or search existing.
